export enum ActionType {
  UPDATE_CELL = "UPDATE_CELL",
  MOVE_CELL = "MOVE_CELL",
  INSERT_CELL_AFTER = "INSERT_CELL_AFTER",
  DELETE_CELL = "DELETE_CELL",
  BUNDLE_START = "BUNDLE_START",
  BUNDLE_COMPLETE = "BUNDLE_COMPLETE",
  INITIALISE_BUNDLER = "INITIALISE_BUNDLER",
  FETCH_CELLS = "FETCH_CELLS",
  FETCH_CELLS_COMPLETE = "FETCH_CELLS_COMPLETE",
  FETCH_CELLS_ERR = "FETCH_CELLS_ERR",
}
